### ISSUE TITLE
Settings : Nextjs 프로젝트 설치 및 개발 환경 세팅

### ISSUE THREAD

**Issue by JuJangGwon** [Network-office/Network-office-FE#1]
## Todo
- [ ] 패키지 매니저 pnpm 설치
- [ ] Nextjs14 버전 설치 
- [ ] elsint & pritter 적용
