### ISSUE TITLE
Settings : Cypress 추가 및 기존 로직 E2E 테스트 코드 

### ISSUE THREAD

**Issue by JuJangGwon** [Network-office/Network-office-FE#113]
## Todos 
- [ ] Cypress 라이브러리 추가
- [ ] Cypress에 MSW 연동 
- [ ] 기존 코드들에 E2E 테스트 코드 추가
